const LOTTO_PRICE = 1000;
const LOTTO_NUM_MIN_RANGE = 1;
const LOTTO_NUM_MAX_RANGE = 45;
const LOTTO_DIGITS = 6;

module.exports = {
  LOTTO_PRICE,
  LOTTO_NUM_MIN_RANGE,
  LOTTO_NUM_MAX_RANGE,
  LOTTO_DIGITS,
};
