const ENTER_LOTTO_PURCHASE_AMOUNT = '구입금액을 입력해 주세요.\n';
const INCLUDE_NOT_NUMBER_IN_PURCHASE_AMOUNT_ERROR = '[ERROR] 구입금액은 숫자여야 합니다.\n';
const START_WITH_ZERO_ERROR = '[ERROR] 구입금액의 첫 자리는 1이상 9이하의 숫자이여야 합니다.';
const NOT_DIVISIBLE_BY_THOUSAND_ERROR = '[ERROR] 구입금액은 1000으로 나누어 떨어져야 합니다.';
const SHOW_NUMBER_OF_LOTTOS = '개를 구매했습니다.';
const ENTER_WINNING_NUMBERS = '당첨 번호를 입력해 주세요.\n';
const INCLUDE_NOT_NUMBER_IN_WINNING_NUMBERS_ERROR = '[ERROR] 당첨번호는 숫자여야 합니다.\n';
const NOT_SIX_WINNING_NUMBERS_ERROR = '[ERROR] 당첨번호는 6개이어야 합니다.';
const WINNING_NUMBER_OUT_OF_RANGE_ERROR = '[ERROR] 당첨번호는 1이상 45이하의 숫자이어야 합니다.';
const WINNING_NUMBERS_DUPLICATED = '[ERROR] 당첨번호는 중복되지 않는 번호로 이루어져야 합니다.';
const ENTER_BONUS_NUMBER = '보너스 번호를 입력해 주세요.\n';
const INCLUDE_NOT_NUMBER_IN_BONUS_NUMBER_ERROR = '[ERROR] 보너스번호는 숫자이어야 합니다.';
const BONUS_NUMBER_OUT_OF_RANGE_ERROR = '[ERROR] 보너스번호는 1이상 45이하의 숫자이어야 합니다.';
const BONUS_NUMBER_DUPLICATED_WITH_WINNING_NUMBERS =
  '[ERROR] 당첨번호와 보너스 번호는 중복되지 않아야 합니다.';

module.exports = {
  GUIDE: {
    ENTER_LOTTO_PURCHASE_AMOUNT,
    SHOW_NUMBER_OF_LOTTOS,
    ENTER_WINNING_NUMBERS,
    ENTER_BONUS_NUMBER,
  },
  ERROR: {
    INCLUDE_NOT_NUMBER_IN_PURCHASE_AMOUNT_ERROR,
    START_WITH_ZERO_ERROR,
    NOT_DIVISIBLE_BY_THOUSAND_ERROR,
    INCLUDE_NOT_NUMBER_IN_WINNING_NUMBERS_ERROR,
    NOT_SIX_WINNING_NUMBERS_ERROR,
    WINNING_NUMBER_OUT_OF_RANGE_ERROR,
    WINNING_NUMBERS_DUPLICATED,
    INCLUDE_NOT_NUMBER_IN_BONUS_NUMBER_ERROR,
    BONUS_NUMBER_OUT_OF_RANGE_ERROR,
    BONUS_NUMBER_DUPLICATED_WITH_WINNING_NUMBERS,
  },
};
