const LOTTO_NUMBER_LENGTH = 6;
const LOTTO_RANGE_BEGIN = 1;
const LOTTO_RANGE_END = 45;

const PRIZE = [5000, 50000, 1500000, 30000000, 2000000000];
const CORRECT_THREE = 0;
const CORRECT_FOUR = 1;
const CORRECT_FIVE = 2;
const CORRECT_FIVE_BONUS = 3;
const CORRECT_SIX = 4;

module.exports = {
  LOTTO_NUMBER_LENGTH,
  LOTTO_RANGE_BEGIN,
  LOTTO_RANGE_END,
  PRIZE,
  CORRECT_THREE,
  CORRECT_FOUR,
  CORRECT_FIVE,
  CORRECT_FIVE_BONUS,
  CORRECT_SIX,
};
