const MIN_LOTTO_NUMBER = 1;
const MAX_LOTTO_NUMBER = 45;
const VALID_LOTTO_NUMBER_LENGTH = 6;
const SIX_MATCH_REWARD = 2000000000;
const BONUS_MATCH_REWARD = 30000000;
const FIVE_MATCH_REWARD = 1500000;
const FOUR_MATCH_REWARD = 50000;
const THREE_MATCH_REWARD = 5000;

module.exports = {
  MIN_LOTTO_NUMBER,
  MAX_LOTTO_NUMBER,
  VALID_LOTTO_NUMBER_LENGTH,
  SIX_MATCH_REWARD,
  BONUS_MATCH_REWARD,
  FIVE_MATCH_REWARD,
  FOUR_MATCH_REWARD,
  THREE_MATCH_REWARD,
};
