const MIN_NUMBER_RANGE = 1;
const MAX_NUMBER_RANGE = 45;
const NUMBERS_LENGTH = 6;
const BONUS_NUMBER_LENGTH = 1;
const PERMISSIBLE_UNITS = 1000;

const THREE_REWARD = 5000;
const FOUR_REWARD = 50000;
const FIVE_REWARD = 1500000;
const FIVE_BONUS_REWARD = 30000000;
const SIX_REWARD = 2000000000;

const MATCHES_THREE_NUMBERS = 3;
const MATCHES_FOUR_NUMBERS = 4;
const MATCHES_FIVE_NUMBERS = 5;
const MATCHES_SIX_NUMBERS = 6;
// export const MIN_NUMBER_RANGE = MIN_NUMBER_RANGE;
// export const MAX_NUMBER_RANGE = MAX_NUMBER_RANGE;
// export const NUMBERS_LENGTH = NUMBERS_LENGTH;
// export const PERMISSIBLE_UNITS = PERMISSIBLE_UNITS;

module.exports = {
  MIN_NUMBER_RANGE: MIN_NUMBER_RANGE,
  MAX_NUMBER_RANGE: MAX_NUMBER_RANGE,
  NUMBERS_LENGTH: NUMBERS_LENGTH,
  PERMISSIBLE_UNITS: PERMISSIBLE_UNITS,
  BONUS_NUMBER_LENGTH: BONUS_NUMBER_LENGTH,
  THREE_REWARD: THREE_REWARD,
  FOUR_REWARD: FOUR_REWARD,
  FIVE_REWARD: FIVE_REWARD,
  FIVE_BONUS_REWARD: FIVE_BONUS_REWARD,
  SIX_REWARD: SIX_REWARD,
  MATCHES_THREE_NUMBERS: MATCHES_THREE_NUMBERS,
  MATCHES_FOUR_NUMBERS: MATCHES_FOUR_NUMBERS,
  MATCHES_FIVE_NUMBERS: MATCHES_FIVE_NUMBERS,
  MATCHES_SIX_NUMBERS: MATCHES_SIX_NUMBERS,
};
