const MIN_NUMBER_RANGE = 1;
const MAX_NUMBER_RANGE = 45;
const NUMBERS_LENGTH = 6;
const PERMISSIBLE_UNITS = 1000;

// export const MIN_NUMBER_RANGE = MIN_NUMBER_RANGE;
// export const MAX_NUMBER_RANGE = MAX_NUMBER_RANGE;
// export const NUMBERS_LENGTH = NUMBERS_LENGTH;
// export const PERMISSIBLE_UNITS = PERMISSIBLE_UNITS;

module.exports = {
  MIN_NUMBER_RANGE: MIN_NUMBER_RANGE,
  MAX_NUMBER_RANGE: MAX_NUMBER_RANGE,
  NUMBERS_LENGTH: NUMBERS_LENGTH,
  PERMISSIBLE_UNITS: PERMISSIBLE_UNITS,
};
