const LOTTO_PRICE = 1000;
const LOTTO_MINIMUM_NUMBER = 1;
const LOTTO_MAXIMUM_NUMBER = 45;
const LOTTO_DIGIT_LENGTH = 6;

const CONSTANTS = {
  LOTTO_PRICE,
  LOTTO_MINIMUM_NUMBER,
  LOTTO_MAXIMUM_NUMBER,
  LOTTO_DIGIT_LENGTH,
};

module.exports = { CONSTANTS };
