const LOTTO_PRICE = 1000;
const LOTTO_MINIMUM_NUMBER = 1;
const LOTTO_MAXIMUM_NUMBER = 45;
const LOTTO_DIGIT_LENGTH = 6;
const FIFTH_PLACE_REWARD = 5000;
const FOURTH_PLACE_REWARD = 50000;
const THIRD_PLACE_REWARD = 1500000;
const SECOND_PLACE_REWARD = 30000000;
const FIRST_PLACE_REWARD = 2000000000;
const CONSTANTS = {
  LOTTO_PRICE,
  LOTTO_MINIMUM_NUMBER,
  LOTTO_MAXIMUM_NUMBER,
  LOTTO_DIGIT_LENGTH,
  FIFTH_PLACE_REWARD,
  FOURTH_PLACE_REWARD,
  THIRD_PLACE_REWARD,
  SECOND_PLACE_REWARD,
  FIRST_PLACE_REWARD,
};

module.exports = { CONSTANTS };
