const LOTTO_PURCHASE = {
  UNIT: 1000,
  MIMIMUM: 1000,
};

const LOTTO_NUMBER = {
  DIVISION: ',',
  LENGTH: 6,
  START_RANGE: 1,
  END_RANGE: 45,
};

module.exports = { LOTTO_PURCHASE, LOTTO_NUMBER };
