const MONEY_ARRAY = [5000, 50000, 15000000, 30000000, 2000000000];

const NAME_ARRAY = ["FIFTH", "FOURTH", "THIRD", "SECOND", "FIRST"];

const FIFTH_INDEX = 0;
const FOURTH_INDEX = 1;
const THIRD_INDEX = 2;
const SECOND_INDEX = 3;
const FIRST_INDEX = 4;

const NUMBER_OF_LOTTO = 6;
const NUMBER_OF_START = 1;
const NUMBER_OF_END = 45;

const MONEY_UNIT = 1000;
const TO_PERCENT = 100;

const STANDARD_FIFTH = 3;
const STANDARD_FOURTH = 4;
const STANDARD_THIRD = 5;
const STANDARD_FIRST = 6;

module.exports = {
  MONEY_ARRAY,
  NAME_ARRAY,
  FIFTH_INDEX,
  FOURTH_INDEX,
  THIRD_INDEX,
  SECOND_INDEX,
  FIRST_INDEX,
  NUMBER_OF_LOTTO,
  NUMBER_OF_START,
  NUMBER_OF_END,
  MONEY_UNIT,
  TO_PERCENT,
  STANDARD_FIFTH,
  STANDARD_FOURTH,
  STANDARD_THIRD,
  STANDARD_FIRST,
};
