const LOTTO_LENGTH_ERROR = "[ERROR] 로또 번호는 6개여야 합니다.";
const LOTTO_TYPE_ERROR = "[ERROR] 로또 번호는 숫자로 구성되어야 합니다";
const LOTTO_DUPLICATE_ERROR = "[ERROR] 로또 번호는 중복되지 않아야 합니다";

const LOTTOS_PRINT = "개를 구매했습니다.";

const MANAGEMENT_WIN_NUMBER_LENGTH_ERROR =
  "[ERROR] 당첨 번호는 6개여야 합니다.";
const MANAGEMENT_WIN_NUMBER_TYPE_ERROR =
  "[ERROR] 당첨 번호는 숫자로 구성되어야 합니다";
const MANAGEMENT_WIN_NUMBER_RANGE_ERROR =
  "[ERROR] 당첨 번호는 1 ~ 45 범위이어야 합니다";
const MANAGEMENT_WIN_NUMBER_DUPLICATE_ERROR =
  "[ERROR] 당첨 번호는 중복되지 않아야 합니다";
const MANAGEMENT_BONUS_NUMBER_TYPE_ERROR =
  "[ERROR] 보너스 번호는 숫자이어야 합니다.";
const MANAGEMENT_BONUS_NUMBER_RANGE_ERROR =
  "[ERROR] 보너스 번호는 1 ~ 45 범위이어야 합니다";
const MANAGEMENT_BONUS_NUMBER_DUPLICATE_ERROR =
  "[ERROR] 보너스 번호는 당첨번호와 중복되지 않아야 합니다";
const MANAGEMENT_WIN_NUMBER_QUERY = "당첨 번호를 입력해 주세요.";
const MANAGEMENT_BONUS_NUMBER_QUERY = "보너스 번호를 입력해 주세요.";

const PAYMEMT_QUERY = "구입금액을 입력해 주세요.";
const PAYMEMT_ZERO_ERROR = "[ERROR] 0보다 큰 숫자를 입력해야 합니다";
const PAYMEMT_TYPE_ERROR = "[ERROR] 숫자만 입력가능합니다";
const PAYMEMT_UNIT_ERROR = "[ERROR] 1000원 단위로 입력해야 합니다";

const STATUS_RESULT_TITLE = "당첨 통계";
const STATUS_RESULT_UNIT = "개";
const STATUS_FIFTH_PLACE = "3개 일치 (5,000원)";
const STATUS_FOURTH_PLACE = "4개 일치 (50,000원)";
const STATUS_THIRD_PLACE = "5개 일치 (1,500,000원)";
const STATUS_SECOND_PLACE = "5개 일치, 보너스 볼 일치 (30,000,000원)";
const STATUS_FIRST_PLACE = "6개 일치 (2,000,000,000원)";

module.exports = {
  LOTTO_LENGTH_ERROR,
  LOTTO_TYPE_ERROR,
  LOTTO_DUPLICATE_ERROR,
  LOTTOS_PRINT,
  MANAGEMENT_WIN_NUMBER_LENGTH_ERROR,
  MANAGEMENT_WIN_NUMBER_TYPE_ERROR,
  MANAGEMENT_WIN_NUMBER_RANGE_ERROR,
  MANAGEMENT_WIN_NUMBER_DUPLICATE_ERROR,
  MANAGEMENT_BONUS_NUMBER_TYPE_ERROR,
  MANAGEMENT_BONUS_NUMBER_RANGE_ERROR,
  MANAGEMENT_BONUS_NUMBER_DUPLICATE_ERROR,
  MANAGEMENT_WIN_NUMBER_QUERY,
  MANAGEMENT_BONUS_NUMBER_QUERY,
  PAYMEMT_QUERY,
  PAYMEMT_ZERO_ERROR,
  PAYMEMT_TYPE_ERROR,
  PAYMEMT_UNIT_ERROR,
  STATUS_RESULT_TITLE,
  STATUS_RESULT_UNIT,
  STATUS_FIFTH_PLACE,
  STATUS_FOURTH_PLACE,
  STATUS_THIRD_PLACE,
  STATUS_SECOND_PLACE,
  STATUS_FIRST_PLACE,
};
