const LOTTO_PRICE = 1000;
const LOTTO_MAX_NUMBER = 45;
const LOTTO_MIN_NUMBER = 1;
const LOTTO_MAX_COUNT = 6;

const INPUT_AMOUNT_MESSAGE = '구입금액을 입력해주세요.';
const INPUT_LOTTO_NUMBERS = '당첨 번호를 입력해 주세요.';
const INPUT_BONUS_NUMBER = '보너스 번호를 입력해 주세요.';

const STATISTICS = '당첨 통계';
const DIVIDER = '---';

const FIRST_PRIZE = '6개 일치 (2,000,000,000원)';
const SECOND_PRIZE = '5개 일치, 보너스 볼 일치 (30,000,000원)';
const THIRD_PRIZE = '5개 일치 (1,500,000원)';
const FOURTH_PRIZE = '4개 일치 (50,000원)';
const FIFTH_PRIZE = '3개 일치 (5,000원)';

const DUPLICATE_ERROR_MESSAGE = '[ERROR] 로또 번호에 중복이 있을 수 없습니다.';
const LOTTO_LENGTH_ERROR_MESSAGE = '[ERROR] 로또 번호는 6개여야 합니다.';
const LOTTO_BOUND_ERROR_MESSAGE =
  '[ERROR] 로또 번호는 1이상 45 이하의 정수여야 합니다.';
const INVALID_INTEGER_ERROR_MESSAGE = '[ERROR] 금액은 정수여야 합니다.';
const INVALID_UNIT_ERROR_MESSAGE = '[ERROR] 금액은 1,000원 단위여야 합니다.';

module.exports = {
  LOTTO_PRICE,
  LOTTO_MAX_NUMBER,
  LOTTO_MIN_NUMBER,
  LOTTO_MAX_COUNT,
  INPUT_AMOUNT_MESSAGE,
  INPUT_LOTTO_NUMBERS,
  INPUT_BONUS_NUMBER,
  STATISTICS,
  DIVIDER,
  FIRST_PRIZE,
  SECOND_PRIZE,
  THIRD_PRIZE,
  FOURTH_PRIZE,
  FIFTH_PRIZE,
  DUPLICATE_ERROR_MESSAGE,
  LOTTO_LENGTH_ERROR_MESSAGE,
  LOTTO_BOUND_ERROR_MESSAGE,
  INVALID_INTEGER_ERROR_MESSAGE,
  INVALID_UNIT_ERROR_MESSAGE,
};
