const LOTTO_PRICE = 1000;
const LOTTO_MAX_NUMBER = 45;
const LOTTO_MIN_NUMBER = 1;

const INPUT_AMOUNT_MESSAGE = '구입금액을 입력해주세요.';
const INPUT_LOTTO_NUMBERS = '당첨 번호를 입력해 주세요.';
const INPUT_BONUS_NUMBER = '보너스 번호를 입력해 주세요.';

const STATISTICS = '당첨 통계';
const DIVIDER = '---';

const FIRST_PRIZE = '2,000,000,000원';
const SECOND_PRIZE = '30,000,000원';
const THIRD_PRIZE = '1,500,000원';
const FOURTH_PRIZE = '50,000원';
const FIFTH_PRIZE = '5,000원';

module.exports = {
  LOTTO_PRICE,
  LOTTO_MAX_NUMBER,
  LOTTO_MIN_NUMBER,
  INPUT_AMOUNT_MESSAGE,
  INPUT_LOTTO_NUMBERS,
  INPUT_BONUS_NUMBER,
  STATISTICS,
  DIVIDER,
  FIRST_PRIZE,
  SECOND_PRIZE,
  THIRD_PRIZE,
  FOURTH_PRIZE,
  FIFTH_PRIZE,
};
