const ENTER_PURCHASE_AMOUNT = 'ENTER_PURCHASE_AMOUNT';
const PLEASE_ENTER_TEXT = '을 입력해 주세요.';

const START_RANDOM_NUMBER = 1;
const END_RANDOM_NUMBER = 45;
const COUNT_PER_LINE = 6;

module.exports = {
  ENTER_PURCHASE_AMOUNT,
  PLEASE_ENTER_TEXT,
  START_RANDOM_NUMBER,
  END_RANDOM_NUMBER,
  COUNT_PER_LINE
};
