const COMMENT = {
  LOTTO_MIN_NUM: 1,
  LOTTO_MAX_NUM: 45,
  LOTTO_NUM_COUNT: 6,
  RANK_NO_MONEY: 0,
  RANK5_MONEY: 5000,
  RANK4_MONEY: 50000,
  RANK3_MONEY: 1500000,
  RANK2_MONEY: 30000000,
  RANK1_MONEY: 2000000000,
  CMM_INPUT_MONEY: '구입금액을 입력해 주세요.\n',
  CMM_INPUT_WINNING: '당첨 번호를 입력해 주세요.\n',
  CMM_INPUT_BONUS: '보너스 번호를 입력해 주세요.\n',
  CMM_BUY_LOTTO: '개를 구매했습니다.',
  CMM_SHOW_STAT: '당첨통계\n---\n',
  CMM_RANK5: '3개 일치 (5,000원) - ',
  CMM_RANK4: '4개 일치 (50,000원) - ',
  CMM_RANK3: '5개 일치 (1,500,000원) - ',
  CMM_RANK2: '5개 일치, 보너스 볼 일치 (30,000,000원) - ',
  CMM_RANK1: '6개 일치 (2,000,000,000원) - ',
  ERR_ONLY_NUM: '[ERROR] 금액은 숫자로 입력해야합니다.',
  ERR_MONEY_MIN: '[ERROR] 최소 입력금액은 1000원입니다.',
  ERR_MONEY_UNIT: '[ERROR] 금액은 1000원단위로 입력해야 합니다',
  ERR_LOTTO_CNT: '[ERROR] 로또 번호는 6개여야 합니다.',
  ERR_SPLIT_SIX: '[ERROR] 당첨번호는 6개로 입력해야 합니다.',
  ERR_NOT_NUM: '[ERROR] 번호는 1부터 45까지의 숫자로 구성되어야 합니다',
  ERR_WINNING_DUP: '[ERROR] 당첨번호는 겹치지 않는 숫자로 입력해야 합니다',
  ERR_BONIUS_DUP: '[ERROR] 보너스번호는 당첨번호와 겹치지 않도록 입력해야합니다',
};

module.exports = COMMENT;
