const ENTER_PURCHASE_AMOUNT = 'ENTER_PURCHASE_AMOUNT';
const ENTER_WINNING_NUMBERS = 'ENTER_WINNING_NUMBERS';
const ENTER_BONUS_NUMBER = 'ENTER_BONUS_NUMBER';
const PLEASE_ENTER_TEXT = '을 입력해 주세요.';

const START_RANDOM_NUMBER = 1;
const END_RANDOM_NUMBER = 45;
const COUNT_PER_LINE = 6;

module.exports = {
  ENTER_PURCHASE_AMOUNT,
  ENTER_WINNING_NUMBERS,
  ENTER_BONUS_NUMBER,
  PLEASE_ENTER_TEXT,
  START_RANDOM_NUMBER,
  END_RANDOM_NUMBER,
  COUNT_PER_LINE
};
